---
- name: install syncthing service
  become: yes
  pacman: name=syncthing state=latest
  notify:
    - restart syncthing systemd service

- name: enable syncthing service
  become: yes
  systemd:
    name: "syncthing@{{ansible_user_id}}"
    enabled: yes
    state: started
