---
- name: install emacs service
  homebrew: name=emacs state=latest
  notify:
    - unload emacs service
    - load emacs service

- name: ensure emacs directory
  file: path=~/.local/var/log state=directory recurse=yes

- name: enable emacs service
  template:
    src: home/Library/LaunchAgents/org.gnu.emacs.plist.j2
    dest: ~/Library/LaunchAgents/org.gnu.emacs.plist
  notify:
    - unload emacs service
    - load emacs service
