---

# dotfiles.yml

dots:
  - ~/.aria2
  - ~/.config/fish
  - ~/.irssi
  - ~/.ssh
  - ~/.xmonad

links:
  - source: ~/.dotfiles/etc/aria2.conf
    dest: ~/.aria2/aria2.conf

  - source: ~/.dotfiles/etc/bashrc
    dest: ~/.bashrc

  - source: ~/.dotfiles/fish/config.fish
    dest: ~/.config/fish/config.fish

  - source: ~/.dotfiles/fish/functions
    dest: ~/.config/fish/functions

  - source: ~/.dotfiles/etc/gitconfig
    dest: ~/.gitconfig

  - source: ~/.dotfiles/etc/hgrc
    dest: ~/.hgrc

  - source: ~/.dotfiles/irssi/scripts
    dest: ~/.irssi/scripts

  - source: ~/.dotfiles/etc/profile
    dest: ~/.profile

  - source: ~/.dotfiles/emacs/spacemacs.d
    dest: ~/.spacemacs.d

  - source: ~/.dotfiles/ssh/config.d
    dest: ~/.ssh/config.d

  - source: ~/.dotfiles/etc/tmux.conf
    dest: ~/.tmux.conf

  - source: ~/.dotfiles/vim/vimperatorrc
    dest: ~/.vimperatorrc

darwin_links:
  - source: ~/.dotfiles/etc/amethyst
    dest: ~/.amethyst

archlinux_links:
  - source: ~/.dotfiles/etc/Xresources
    dest: ~/.Xresources

  - source: ~/.dotfiles/etc/xinitrc
    dest: ~/.xinitrc

  - source: ~/.dotfiles/etc/xmobarrc
    dest: ~/.xmobarrc

  - source: ~/.dotfiles/etc/xmonad.hs
    dest: ~/.xmonad/xmonad.hs

  - source: ~/.dotfiles/etc/xprofile
    dest: ~/.xprofile

# projects.yml

projects:
  - ~/Projects/_Vendor
  - ~/Projects/_Other
