---
- name: install fish shell
  homebrew: name=fish state=latest

- name: appending fish to list of shells
  become: yes
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/fish
    state: present

- name: changing default shell
  become: yes
  user: name={{ansible_user_id}} shell=/usr/local/bin/fish
