---
- name: install go
  homebrew: name=golang state=latest
  when: ansible_os_family == "Darwin"
  register: node_installed

- name: install go
  become: yes
  pacman: name=go state=latest
  when: ansible_os_family == "Archlinux"
  register: node_installed

- name: ensure gopath directory
  file:
    path: ~/Projects/_Go/
    state: directory
    recurse: yes

- name: install go packages
  command: go get -u -v {{item}}
  args:
    creates: "~/Projects/_Go/src/{{item}}"
  environment:
    GOPATH: "{{ansible_env.HOME}}/Projects/_Go/"
  with_items: "{{go_packages}}"
