---
- include: "golang_{{ansible_os_family|lower}}.yml"

- name: ensure gopath directory
  file:
    path: ~/Projects/_Go/
    state: directory
    recurse: yes

- name: install go packages
  command: go get -u -v {{item}}
  args:
    creates: "~/Projects/_Go/src/{{item}}"
  environment:
    GOPATH: "{{ansible_env.HOME}}/Projects/_Go/"
  with_items: "{{go_packages}}"
