---
- include: "nodejs_{{ansible_os_family|lower}}.yml"

- name: configure npm prefix
  command: npm config set prefix ~/.local
  when: "node_installed.changed"

- name: install npm packages
  npm:
    name: "{{item}}"
    global: true
    state: latest
  with_items: "{{node_packages}}"
