---
- name: install node
  homebrew: name=node state=latest
  when: ansible_os_family == "Darwin"
  register: node_installed

- name: install node
  become: yes
  pacman: name={{item}} state=latest
  when: ansible_os_family == "Archlinux"
  register: node_installed
  with_items:
    - nodejs
    - npm

- name: configure npm prefix
  command: npm config set prefix ~/.local
  when: "node_installed.changed"

- name: install npm packages
  npm:
    name: "{{item}}"
    global: true
    state: latest
  with_items: "{{node_packages}}"

- name: install custom typescript-tools
  npm:
    name: 'https://github.com/sirn/typescript-tools.git#tsconfig'
    global: true
