---
- name: install rust
  homebrew: name=rust state=latest
  when: ansible_os_family == "Darwin"

- name: install rust
  become: yes
  pacman: name=rust state=latest
  when: ansible_os_family == "Archlinux"

- name: install rustfmt
  command: cargo install rustfmt
  args:
    creates: ~/.cargo/bin/rustfmt

- name: install racer
  command: cargo install racer
  args:
    creates: ~/.cargo/bin/racer

- name: determine rust version
  shell: rustc --version | cut -d " " -f 2 -
  register: rust_version
  changed_when: false

- name: create rust source directory
  file: path=~/.local/src/rust state=directory recurse=yes

# https://github.com/ansible/ansible/issues/11348
- name: extract rust source
  shell: |
    mkdir -p ~/.local/src/rust/rustc-{{rust_version.stdout}} &&
    curl https://static.rust-lang.org/dist/rustc-{{rust_version.stdout}}-src.tar.gz |
    tar -xvzf - --strip-components 1 -C ~/.local/src/rust/rustc-{{rust_version.stdout}}
  args:
    warn: no
    creates: "~/.local/src/rust/rustc-{{rust_version.stdout}}"

- name: link rust source
  file:
    src: "~/.local/src/rust/rustc-{{rust_version.stdout}}"
    dest: ~/.local/src/rust/current
    state: link
