---
- name: install golang plugin via asdf
  command: ~/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang
  args:
    creates: ~/.asdf/plugins/golang

- name: install golang {{golang_version}} via asdf
  command: ~/.asdf/bin/asdf install golang {{golang_version}}
  args:
    creates: ~/.asdf/installs/golang/{{golang_version}}
  notify:
    - update default golang
    - update golang shims

- name: ensure gopath directory
  file:
    path: ~/Dev/go/
    state: directory
    recurse: yes

- name: install golang packages
  command: ~/.asdf/installs/golang/{{golang_version}}/go/bin/go get -u -v {{item}}
  args:
    creates: "~/Dev/go/src/{{item}}"
  environment:
    GOPATH: "{{ansible_env.HOME}}/Dev/go/"
    GOROOT: "{{ansible_env.HOME}}/.asdf/installs/golang/{{golang_version}}/go"
  with_items: "{{golang_packages}}"
  notify:
    - update golang shims
