---
- name: install minikube plugin via asdf
  git:
    repo: https://github.com/alvarobp/asdf-minikube.git
    dest: ~/.asdf/plugins/minikube

- name: install minikube {{minikube_version}} via asdf
  command: ~/.asdf/bin/asdf install minikube {{minikube_version}}
  args:
    creates: ~/.asdf/installs/minikube/{{minikube_version}}
  notify:
    - update default minikube
    - update minikube shims
