---
- name: ensure nodejs keyring directory
  file:
    path: ~/.asdf/keyrings/nodejs
    mode: 0700
    state: directory

- name: import nodejs release team keyring
  command: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  args:
    creates: ~/.asdf/keyrings/nodejs/trustdb.gpg
  environment:
    GNUPGHOME: "{{ansible_env.HOME}}/.asdf/keyrings/nodejs"

- name: install nodejs plugin via asdf
  git:
    repo: https://github.com/asdf-vm/asdf-nodejs.git
    dest: ~/.asdf/plugins/nodejs

- name: install nodejs {{nodejs_version}} via asdf
  command: ~/.asdf/bin/asdf install nodejs {{nodejs_version}}
  args:
    creates: ~/.asdf/installs/nodejs/{{nodejs_version}}
  notify:
    - update default nodejs
    - update nodejs shims
  environment:
    GNUPGHOME: "{{ansible_env.HOME}}/.asdf/keyrings/nodejs"

- name: configure npm prefix
  command: ~/.asdf/installs/nodejs/{{nodejs_version}}/bin/npm config set prefix ~/.local
  args:
    creates: ~/.npmrc

- name: install nodejs packages
  npm:
    name: "{{item}}"
    global: true
    state: latest
    executable: ~/.asdf/installs/nodejs/{{nodejs_version}}/bin/npm
  with_items: "{{nodejs_packages}}"
  notify:
    - update nodejs shims
