---
- name: install python plugin via asdf
  command: ~/.asdf/bin/asdf plugin-add python https://github.com/tuvistavie/asdf-python
  args:
    creates: ~/.asdf/plugins/python

- name: install python {{python2_version}} via asdf
  command: ~/.asdf/bin/asdf install python {{python2_version}}
  args:
    creates: ~/.asdf/installs/python/{{python2_version}}
  notify:
    - update default python
    - update python shims

- name: install python {{python3_version}} via asdf
  command: ~/.asdf/bin/asdf install python {{python3_version}}
  args:
    creates: ~/.asdf/installs/python/{{python3_version}}
  notify:
    - update default python
    - update python shims

- name: install python2 packages
  pip:
    name: "{{item}}"
    state: latest
    executable: ~/.asdf/installs/python/{{python2_version}}/bin/pip
    chdir: ~/.asdf/installs/python/{{python2_version}}
  with_items: "{{python2_packages}}"
  notify:
    - update python shims

- name: install python3 packages
  pip:
    name: "{{item}}"
    state: latest
    executable: ~/.asdf/installs/python/{{python3_version}}/bin/pip
    chdir: ~/.asdf/installs/python/{{python3_version}}
  with_items: "{{python3_packages}}"
  notify:
    - update python shims
