---
- name: check cower installation
  shell: pacman -Q |grep cower |head -n1
  register: check_cower
  changed_when: not check_cower.stdout

- name: download tarball for cower
  get_url:
    url: "https://aur.archlinux.org/cgit/aur.git/snapshot/cower.tar.gz"
    dest: /tmp/
  register: download_cower
  when: not check_cower.stdout

- name: extract tarball for cower
  unarchive:
    src: "{{download_cower.dest}}"
    dest: /tmp
  register: extract_cower
  when: download_cower.changed

# Use skippgpcheck for now as GPG is broken (2.1.17)
#
# - name: import gpg key for cower
#   shell: gpg --recv-keys --keyserver hkp://pgp.mit.edu 1EB2638FF56C0C53
#   when: not check_cower.stdout

- name: build package for cower
  command: >-
    makepkg --noconfirm --noprogressbar --skippgpcheck -mfs
    chdir=/tmp/cower
  when: not check_cower.stdout

- name: install cower
  become: yes
  shell: >-
    pacman --noconfirm --noprogressbar --needed -U *.pkg.tar.xz
    chdir=/tmp/cower
  register: install_cower
  changed_when: install_cower.stdout.find('there is nothing to do') == -1
  when: not check_cower.stdout
