---
# packages/darwin_brew

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes

# packages/darwin_mpv

- name: link mpv
  command: brew linkapps mpv
  ignore_errors: yes
  args:
    warn: no

# services/darwin_env

- name: unload environment launchd service
  command: launchctl unload ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

- name: load environment launchd service
  command: launchctl load ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

# services/darwin_syncthing

- name: unload syncthing launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

- name: load syncthing launchd service
  command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

# services/darwin_unbound

- name: unload unbound launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

- name: load unbound launchd service
  command: launchctl load ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes
