---
# packages/homebrew

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes

# packages/python

- name: update default python
  command: ~/.pyenv/bin/pyenv global {{python2_version}} {{python3_version}}

- name: update pyenv shims
  command: ~/.pyenv/bin/pyenv rehash

# packages/ruby

- name: update default ruby
  command: ~/.rbenv/bin/rbenv global {{ruby_version}}

- name: update rbenv shims
  command: ~/.rbenv/bin/rbenv rehash

# services/env

- name: unload environment service
  command: launchctl unload ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

- name: load environment service
  command: launchctl load ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

# services/syncthing

- name: unload syncthing service
  command: launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

- name: load syncthing service
  command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

# services/unbound

- name: unload unbound service
  command: launchctl unload ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

- name: load unbound service
  command: launchctl load ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes
