---

# packages/archlinux_pacman

- name: upgrade pacman packages
  become: yes
  pacman: upgrade=yes

# packages/acrhlinux_aur_pacaur

- name: upgrade pacaur packages
  pacaur: upgrade=yes

# packages/darwin_brew

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes

# packages/darwin_mpv

- name: link mpv
  command: brew linkapps mpv
  ignore_errors: yes
  args:
    warn: no

# services/archlinux_nfs

- name: restart nfs-server systemd service
  become: yes
  systemd:
    name: "nfs-server"
    daemon_reload: yes
    state: restarted

# services/archlinux_redshift

- name: restart redshift systemd service
  systemd:
    name: "redshift"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux_syncthing

- name: restart syncthing systemd service
  become: yes
  systemd:
    name: "syncthing@{{ansible_user_id}}"
    daemon_reload: yes
    state: restarted

# service/archlinux_unbound

- name: restart unbound systemd service
  become: yes
  systemd:
    name: "unbound"
    daemon_reload: yes
    state: restarted

# services/darwin_env

- name: unload environment launchd service
  command: launchctl unload ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

- name: load environment launchd service
  command: launchctl load ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

# services/darwin_syncthing

- name: unload syncthing launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

- name: load syncthing launchd service
  command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

# services/darwin_unbound

- name: unload unbound launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

- name: load unbound launchd service
  command: launchctl load ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

# custom/python

- name: update default python
  command: ~/.pyenv/bin/pyenv global {{python2_version}} {{python3_version}}

- name: update pyenv shims
  command: ~/.pyenv/bin/pyenv rehash

# custom/ruby

- name: update default ruby
  command: ~/.rbenv/bin/rbenv global {{ruby_version}}

- name: update rbenv shims
  command: ~/.rbenv/bin/rbenv rehash
