---

# packages/archlinux/pacman

- name: upgrade pacman packages
  become: yes
  pacman: upgrade=yes

# packages/acrhlinux/aur_pacaur

- name: upgrade pacaur packages
  pacaur: upgrade=yes

# packages/darwin/brew

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes

# services/archlinux/docker

- name: restart docker systemd service
  systemd:
    name: "docker"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/mpd

- name: restart mpd systemd service
  systemd:
    name: "mpd"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/nfs

- name: restart nfs-server systemd service
  become: yes
  systemd:
    name: "nfs-server"
    daemon_reload: yes
    state: restarted

# services/archlinux/redshift

- name: restart redshift systemd service
  systemd:
    name: "redshift"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/syncthing

- name: restart syncthing systemd service
  become: yes
  systemd:
    name: "syncthing@{{ansible_user_id}}"
    daemon_reload: yes
    state: restarted

# services/archlinux/unbound

- name: restart unbound systemd service
  become: yes
  systemd:
    name: "unbound"
    daemon_reload: yes
    state: restarted

# services/darwin/env

- name: unload environment launchd service
  command: launchctl unload ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

- name: load environment launchd service
  command: launchctl load ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

# services/darwin/ethereum

- name: unload ethereum launchd service
  command: launchctl unload ~/Library/LaunchAgents/org.ethereum.ethereum.plist
  ignore_errors: yes

- name: load ethereum launchd service
  command: launchctl load ~/Library/LaunchAgents/org.ethereum.ethereum.plist
  ignore_errors: yes

# services/darwin/syncthing

- name: unload syncthing launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

- name: load syncthing launchd service
  command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes

# services/darwin/unbound

- name: unload unbound launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

- name: load unbound launchd service
  command: launchctl load ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

# lang/elixir

- name: update default elixir
  command: ~/.asdf/bin/asdf global elixir {{elixir_version}}

- name: update elixir shims
  command: ~/.asdf/bin/asdf reshim elixir

# lang/erlang

- name: update default erlang
  command: ~/.asdf/bin/asdf global erlang {{erlang_version}}

- name: update erlang shims
  command: ~/.asdf/bin/asdf reshim erlang

# lang/golang

- name: update default golang
  command: ~/.asdf/bin/asdf global golang {{golang_version}}

- name: update golang shims
  command: ~/.asdf/bin/asdf reshim golang

# lang/nodejs

- name: update default nodejs
  command: ~/.asdf/bin/asdf global nodejs {{nodejs_version}}

- name: update nodejs shims
  command: ~/.asdf/bin/asdf reshim nodejs

# lang/python

- name: update default python
  command: ~/.asdf/bin/asdf global python {{python2_version}} {{python3_version}}

- name: update python shims
  command: ~/.asdf/bin/asdf reshim python

# lang/ruby

- name: update default ruby
  command: ~/.asdf/bin/asdf global ruby {{ruby_version}}

- name: update ruby shims
  command: ~/.asdf/bin/asdf reshim ruby

# lang/rust

- name: update default rust
  command: ~/.asdf/bin/asdf global rust {{rust_version}}

- name: update rust shims
  command: ~/.asdf/bin/asdf reshim rust
