---
- name: prepare dot directories
  file: path={{item}} state=directory recurse=yes
  with_items: "{{dots}}"

- name: link files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
  with_items: "{{links}}"

- name: link darwin-specific files and directories
  file:
    src: "{{item.source}}"
    path: "{{item.dest}}"
    state: link
  with_items: "{{darwin_links}}"
  when: ansible_os_family == "Darwin"
