---
- name: prepare sudoers directory
  file: path=/etc/sudoers.d state=directory recurse=yes

- name: adding vagrant sudoers
  become: yes
  copy:
    src: etc/sudoers.d/01_vagrant
    dest: /etc/sudoers.d/01_vagrant
