---
- name: update nix channels
  nix: update_channels=yes

- name: install nix packages
  nix:
    name: "{{item}}"
    state: present
    expr: ~/.dotfiles/nix/custom-packages.nix
  with_items: "{{packages}}"

- name: install attributed nix packages
  nix:
    name: "{{item}}"
    expr: "<nixpkgs>"
    state: present
    attr: true
  with_items: "{{attributed_packages}}"

- name: upgrade nix packages
  nix: upgrade_packages=yes
