---
- name: initialize homebrew taps
  homebrew_tap: tap={{item}} state=present
  with_items: "{{taps}}"

- name: update homebrew
  homebrew: update_homebrew=yes

- name: install homebrew packages
  homebrew: name={{item}} state=present
  with_items: "{{packages}}"

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes
