---
- name: install pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: ~/.pyenv
    force: yes

- name: install python {{python_version}}
  command: ~/.pyenv/bin/pyenv install {{python_version}}
  args:
    creates: ~/.pyenv/versions/{{python_version}}
  register: python_installed

- name: install pypy {{pypy_version}}
  command: ~/.pyenv/bin/pyenv install pypy-{{pypy_version}}
  args:
    creates: ~/.pyenv/versions/pypy-{{pypy_version}}

# Ansible PYTHONPATH will conflict with Pip's PYTHONPATH
# and will cause some package included in Ansible to not
# installable (e.g. six).
- name: install eggs
  pip:
    name: "{{item}}"
    state: latest
    executable: ~/.pyenv/versions/{{python_version}}/bin/pip
    chdir: ~/.pyenv/versions/{{python_version}}
  with_items: "{{python_eggs}}"
  register: python_eggs_installed
  environment:
    PYTHONPATH:

- name: update default python
  command: ~/.pyenv/bin/pyenv global {{python_version}}
  when: "python_installed.changed"

- name: update pyenv shims
  command: ~/.pyenv/bin/pyenv rehash
  when: "python_eggs_installed.changed"
