---
- name: install pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: ~/.pyenv
    force: yes

- name: install python {{python2_version}}
  command: ~/.pyenv/bin/pyenv install {{python2_version}}
  args:
    creates: ~/.pyenv/versions/{{python2_version}}
  register: python2_installed

- name: install python {{python3_version}}
  command: ~/.pyenv/bin/pyenv install {{python3_version}}
  args:
    creates: ~/.pyenv/versions/{{python3_version}}
  register: python3_installed

- name: install pypy {{pypy_version}}
  command: ~/.pyenv/bin/pyenv install pypy-{{pypy_version}}
  args:
    creates: ~/.pyenv/versions/pypy-{{pypy_version}}

# Ansible PYTHONPATH will conflict with Pip's PYTHONPATH
# and will cause some package included in Ansible to not
# installable (e.g. six).
- name: install python {{python2_version}} eggs
  pip:
    name: "{{item}}"
    state: latest
    executable: ~/.pyenv/versions/{{python2_version}}/bin/pip
    chdir: ~/.pyenv/versions/{{python2_version}}
  with_items: "{{python2_eggs}}"
  register: python2_eggs_installed
  environment:
    PYTHONPATH:

- name: install python {{python3_version}} eggs
  pip:
    name: "{{item}}"
    state: latest
    executable: ~/.pyenv/versions/{{python3_version}}/bin/pip
    chdir: ~/.pyenv/versions/{{python3_version}}
  with_items: "{{python3_eggs}}"
  register: python3_eggs_installed
  environment:
    PYTHONPATH:

- name: update default python
  command: ~/.pyenv/bin/pyenv global {{python2_version}} {{python3_version}}
  when: "python2_installed.changed or python3_installed.changed"

- name: update pyenv shims
  command: ~/.pyenv/bin/pyenv rehash
  when: "python2_eggs_installed.changed or python3_eggs_installed.changed"
