---
- name: install python {{python_version}}
  command: pyenv install {{python_version}}
  args:
    creates: ~/.pyenv/versions/{{python_version}}
  register: python_installed

- name: install eggs
  command: ~/.pyenv/versions/2.7.11/bin/pip install --upgrade {{item}}
  with_items: python_eggs
  when: "python_installed.changed"

- name: update default python
  command: /usr/local/bin/pyenv global {{python_version}}
  when: "python_installed.changed"

- name: update pyenv shims
  command: /usr/local/bin/pyenv rehash
  when: "python_installed.changed"
