---
- name: install python {{python_version}}
  command: pyenv install {{python_version}}
  args:
    creates: ~/.pyenv/versions/{{python_version}}
  register: python_installed

- name: install eggs
  pip:
    name: "{{item}}"
    state: latest
    executable: ~/.pyenv/versions/{{python_version}}/bin/pip
  with_items: python_eggs
  register: python_eggs_installed

- name: update default python
  command: /usr/local/bin/pyenv global {{python_version}}
  when: "python_installed.changed"

- name: update pyenv shims
  command: /usr/local/bin/pyenv rehash
  when: "python_eggs_installed.changed"
