---
- name: install ruby {{ruby_version}}
  command: rbenv install {{ruby_version}}
  args:
    creates: ~/.rbenv/versions/{{ruby_version}}
  register: ruby_installed

- name: install gems
  command: ~/.rbenv/versions/{{ruby_version}}/bin/gem install {{item}}
  with_items: ruby_gems
  when: "ruby_installed.changed"

- name: update default ruby
  command: /usr/local/bin/rbenv global {{ruby_version}}
  when: "ruby_installed.changed"

- name: update rbenv shims
  command: /usr/local/bin/rbenv rehash
  when: "ruby_installed.changed"
