---
- name: install ruby {{ruby_version}}
  command: rbenv install {{ruby_version}}
  args:
    creates: ~/.rbenv/versions/{{ruby_version}}
  register: ruby_installed

- name: install gems
  gem:
    name: "{{item}}"
    state: latest
    user_install: False
    executable: ~/.rbenv/versions/{{ruby_version}}/bin/gem
  with_items: "{{ruby_gems}}"
  register: ruby_gems_installed

- name: update default ruby
  command: /usr/local/bin/rbenv global {{ruby_version}}
  when: "ruby_installed.changed"

- name: update rbenv shims
  command: /usr/local/bin/rbenv rehash
  when: "ruby_gems_installed.changed"
