---
- name: install {{shell}} shell
  homebrew: name={{shell}} state=latest

- name: appending {{shell}} to list of shells
  become: yes
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/{{shell}}
    state: present
  register: fish_append

- name: changing default shell
  become: yes
  command: chsh -s /usr/local/bin/{{shell}} {{ansible_user_id}}
  when: "fish_append.changed"
