---
- name: install syncthing service
  homebrew: name=syncthing state=latest
  notify:
    - unload syncthing launchd service
    - load syncthing launchd service

- name: ensure syncthing directory
  file: path=~/.local/var/log state=directory recurse=yes

- name: enable syncthing service
  template:
    src: home/Library/LaunchAgents/net.syncthing.syncthing.plist.j2
    dest: ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  notify:
    - unload syncthing launchd service
    - load syncthing launchd service
