---

# packages/archlinux/pacman

pacman_packages:
  - adobe-source-code-pro-fonts
  - adobe-source-han-sans-jp-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - aria2
  - curl
  - dnsutils
  - emacs
  - feh
  - ffmpeg
  - firefox
  - ghc
  - git
  - gnucash
  - gnupg
  - graphviz
  - hub
  - ibus
  - imagemagick
  - ipcalc
  - jq
  - keychain
  - mercurial
  - moreutils
  - mpv
  - mupdf
  - neovim
  - net-tools
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - onboard
  - openssh
  - openssl
  - rfkill
  - ripgrep
  - rtmpdump
  - rxvt-unicode
  - scrot
  - shellcheck
  - socat
  - thunderbird
  - tmux
  - tree
  - ttf-dejavu
  - vagrant
  - virtualbox
  - whois
  - xfce4
  - xmonad
  - xmonad-contrib
  - xsel
  - xz
  - yarn
  - youtube-dl

aur_keys:
  - 5A92E04305696D78

aur_packages:
  - arcanist-git
  - direnv
  - dmenu-xyw-mouse-msel
  - ghq
  - git-lfs
  - google-cloud-sdk
  - hugo
  - ibus-libthai
  - ibus-mozc
  - kubernetes-helm
  - leiningen
  - minikube-bin
  - packer-io
  - pepper-flash
  - terraform
  - virtualbox-ext-oracle
  - vivaldi
  - vivaldi-ffmpeg-codecs
  - vivaldi-widevine
  - xcape

# packages/darwin/brew

brew_taps:
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions
  - neovim/neovim
  - railwaycat/emacsmacport

brew_packages:
  - arcanist
  - aria2
  - asciinema
  - blueutil
  - carthage
  - cocoapods
  - cocot
  - coreutils
  - curl
  - direnv
  - emacs
  - ffmpeg
  - fswatch
  - ghc
  - ghq
  - git
  - git-flow
  - git-lfs
  - gpg
  - graphviz
  - hub
  - hugo
  - imagemagick
  - ipcalc
  - jq
  - keychain
  - kubernetes-helm
  - leiningen
  - mercurial
  - moreutils
  - neovim
  - openssh
  - openssl
  - packer
  - pinentry-mac
  - reattach-to-user-namespace
  - ripgrep
  - rtmpdump
  - shellcheck
  - socat
  - terraform
  - tmux
  - trash
  - tree
  - xhyve
  - xz
  - yarn
  - youtube-dl

# packages/darwin/cask

cask_taps:
  - buo/cask-upgrade
  - caskroom/cask
  - caskroom/drivers
  - caskroom/fonts
  - caskroom/versions

cask_packages:
  - alfred
  - amethyst
  - bartender
  - charles
  - choosy
  - dropshare
  - emacs-mac
  - firefox
  - flash-ppapi
  - forklift
  - gnucash
  - google-cloud-sdk
  - hazel
  - imagealpha
  - imageoptim
  - iterm2
  - java
  - keyboard-maestro
  - little-snitch
  - mactex
  - micro-snitch
  - microsoft-office
  - minikube
  - mpv
  - omnifocus
  - omnigraffle
  - omnioutliner
  - paw
  - screens
  - sketch
  - spotify
  - the-unarchiver
  - thunderbird
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - viscosity
  - vivaldi
  - xquartz

cask_fonts:
  - font-iosevka
  - font-source-code-pro
  - font-source-sans-pro

# packages/darwin/mas

mas_packages:
  - { id: 407963104, app: "Pixelmator" }
  - { id: 411643860, app: "DaisyDisk" }
  - { id: 413965349, app: "Soulver" }
  - { id: 443987910, app: "1Password" }
  - { id: 455545700, app: "BitPerfect" }
  - { id: 497799835, app: "Xcode" }
  - { id: 523620159, app: "CleanMyDrive 2" }
  - { id: 539883307, app: "LINE" }
  - { id: 557168941, app: "Tweetbot" }
  - { id: 775737590, app: "iA Writer" }
  - { id: 873245660, app: "Spillo" }
  - { id: 880001334, app: "Reeder" }
  - { id: 889428659, app: "xScope" }
  - { id: 890031187, app: "Marked 2" }
  - { id: 924726344, app: "Deliveries" }
  - { id: 937984704, app: "Amphetamine" }
  - { id: 975937182, app: "Day One" }
  - { id: 1077036385, app: "Fluid Browser" }
  - { id: 1107421413, app: "1Blocker" }

# lang/elixir

elixir_version: 1.5.1-otp-20

# lang/erlang

erlang_version: 20.1

# lang/kubectl

kubectl_version: 1.8.6

# lang/nodejs

nodejs_version: 8.4.0

nodejs_packages:
  - autoprefixer
  - js-beautify
  - localtunnel
  - nativefier
  - postcss
  - postcss-cli
  - tern
  - tslint
  - typescript

# lang/golang

golang_version: 1.8.3

golang_packages:
  - github.com/nsf/gocode
  - github.com/rogpeppe/godef
  - golang.org/x/tools/cmd/guru
  - golang.org/x/tools/cmd/gorename
  - golang.org/x/tools/cmd/goimports

# lang/python

python2_version: 2.7.13

python2_packages:
  - ansible

python3_version: 3.6.2

python3_packages:
  - autoflake
  - glances
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pipenv
  - pyqt5
  - virtualenv

# lang/ruby

ruby_version: 2.4.1

ruby_packages:
  - bundler
  - middleman
  - pry
  - sqlint

# lang/rust

rust_version: 1.19.0

rust_packages:
  - racer
  - rustfmt
