---
- name: enable syncthing service
  copy:
    src: home/Library/LaunchAgents/net.syncthing.syncthing.plist
    dest: ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  register: syncthing_enabled

- name: unloading syncthing service
  command: launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes
  when: "syncthing_enabled.changed"

- name: loading syncthing service
  command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes
  when: "syncthing_enabled.changed"
