---
- name: ensure syncthing directory
  file: path=~/.local/var/log state=directory

- name: enable syncthing service
  template:
    src: home/Library/LaunchAgents/net.syncthing.syncthing.plist.j2
    dest: ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  register: syncthing_enabled

- name: unloading syncthing service
  command: launchctl unload ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes
  when: "syncthing_enabled.changed or packages_updated.changed"

- name: loading syncthing service
  command: launchctl load ~/Library/LaunchAgents/net.syncthing.syncthing.plist
  ignore_errors: yes
  when: "syncthing_enabled.changed or packages_updated.changed"
